/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\Administrator\\Downloads\\vuepress-template-main\\Ts_Notes\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-ec3edd24",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec3edd24").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-24b3234a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24b3234a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-bf40aa1a",
    path: "/guide/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf40aa1a").then(next)
    },
  },
  {
    name: "v-66263553",
    path: "/guide/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66263553").then(next)
    },
  },
  {
    name: "v-60582520",
    path: "/resource.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60582520").then(next)
    },
  },
  {
    name: "v-d648b584",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d648b584").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-7f9886d1",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f9886d1").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-7c9fedfc",
    path: "/zh/guide/anyType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c9fedfc").then(next)
    },
  },
  {
    name: "v-6629a2b0",
    path: "/zh/guide/arrayType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6629a2b0").then(next)
    },
  },
  {
    name: "v-367252c8",
    path: "/zh/guide/interface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-367252c8").then(next)
    },
  },
  {
    name: "v-9192ae08",
    path: "/zh/guide/theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9192ae08").then(next)
    },
  },
  {
    name: "v-483a389a",
    path: "/zh/guide/plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-483a389a").then(next)
    },
  },
  {
    name: "v-13775f1a",
    path: "/zh/guide/baseDataType.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13775f1a").then(next)
    },
  },
  {
    name: "v-72d17cad",
    path: "/zh/resource.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72d17cad").then(next)
    },
  },
  {
    name: "v-5c8be7ba",
    path: "/zh/guide/function.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c8be7ba").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]