/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/Ts_notes/",
  "headTags": [],
  "pages": [
    {
      "title": "Guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-ec3edd24",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Why build this template website?",
          "slug": "why-build-this-template-website"
        },
        {
          "level": 2,
          "title": "Usage",
          "slug": "usage"
        },
        {
          "level": 3,
          "title": "Step 1",
          "slug": "step-1"
        },
        {
          "level": 3,
          "title": "Step 2",
          "slug": "step-2"
        },
        {
          "level": 3,
          "title": "Step 3",
          "slug": "step-3"
        },
        {
          "level": 3,
          "title": "Step 4",
          "slug": "step-4"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "VuePress Template",
        "tagline": "Template · Theme · Plugin",
        "actionText": "Get Started →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Template",
            "details": "Rich templates"
          },
          {
            "title": "Theme",
            "details": "Custom theme"
          },
          {
            "title": "Plugin",
            "details": "Multiple plugins"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present OpenHacking"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-24b3234a",
      "path": "/"
    },
    {
      "title": "Plugin",
      "frontmatter": {},
      "regularPath": "/guide/plugin.html",
      "relativePath": "guide/plugin.md",
      "key": "v-bf40aa1a",
      "path": "/guide/plugin.html",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Plugins List",
          "slug": "plugins-list"
        },
        {
          "level": 3,
          "title": "Niche Plugins",
          "slug": "niche-plugins"
        },
        {
          "level": 3,
          "title": "Official Plugins",
          "slug": "official-plugins"
        }
      ]
    },
    {
      "title": "Theme",
      "frontmatter": {},
      "regularPath": "/guide/theme.html",
      "relativePath": "guide/theme.md",
      "key": "v-66263553",
      "path": "/guide/theme.html",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Theme List",
          "slug": "theme-list"
        }
      ]
    },
    {
      "title": "Resources List",
      "frontmatter": {},
      "regularPath": "/resource.html",
      "relativePath": "resource.md",
      "key": "v-60582520",
      "path": "/resource.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "VuePress模板",
        "tagline": "模板 · 主题 · 插件",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "模板",
            "details": "丰富的模板"
          },
          {
            "title": "主题",
            "details": "自定义主题"
          },
          {
            "title": "插件",
            "details": "多种插件"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present OpenHacking"
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-d648b584",
      "path": "/zh/"
    },
    {
      "title": "指南",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-7f9886d1",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "为什么建这个模板站？",
          "slug": "为什么建这个模板站"
        },
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 3,
          "title": "第一步",
          "slug": "第一步"
        },
        {
          "level": 3,
          "title": "第二步",
          "slug": "第二步"
        },
        {
          "level": 3,
          "title": "第三步",
          "slug": "第三步"
        },
        {
          "level": 3,
          "title": "第四步",
          "slug": "第四步"
        }
      ]
    },
    {
      "title": "1、any类型",
      "frontmatter": {},
      "regularPath": "/zh/guide/anyType.html",
      "relativePath": "zh/guide/anyType.md",
      "key": "v-7c9fedfc",
      "path": "/zh/guide/anyType.html",
      "headers": [
        {
          "level": 3,
          "title": "1、any类型",
          "slug": "_1、any类型"
        },
        {
          "level": 3,
          "title": "2、unknown 类型",
          "slug": "_2、unknown-类型"
        }
      ]
    },
    {
      "title": "本部分主要介绍数组类型的相关概念",
      "frontmatter": {},
      "regularPath": "/zh/guide/arrayType.html",
      "relativePath": "zh/guide/arrayType.md",
      "key": "v-6629a2b0",
      "path": "/zh/guide/arrayType.html",
      "headers": [
        {
          "level": 2,
          "title": "本部分主要介绍数组类型的相关概念",
          "slug": "本部分主要介绍数组类型的相关概念"
        },
        {
          "level": 3,
          "title": "1、类型[]",
          "slug": "_1、类型"
        },
        {
          "level": 3,
          "title": "2、数组泛型",
          "slug": "_2、数组泛型"
        },
        {
          "level": 3,
          "title": "3、用接口表示数组",
          "slug": "_3、用接口表示数组"
        },
        {
          "level": 3,
          "title": "4、多维数组",
          "slug": "_4、多维数组"
        },
        {
          "level": 3,
          "title": "5、arguments 类数组",
          "slug": "_5、arguments-类数组"
        },
        {
          "level": 3,
          "title": "6、any在数组中的应用",
          "slug": "_6、any在数组中的应用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/guide/interface.html",
      "relativePath": "zh/guide/interface.md",
      "key": "v-367252c8",
      "path": "/zh/guide/interface.html",
      "headers": [
        {
          "level": 3,
          "title": "1、对象的类型",
          "slug": "_1、对象的类型"
        },
        {
          "level": 3,
          "title": "2、interface 合并与继承",
          "slug": "_2、interface-合并与继承"
        },
        {
          "level": 3,
          "title": "3、interface中定义一个可选属性",
          "slug": "_3、interface中定义一个可选属性"
        },
        {
          "level": 3,
          "title": "4、任意属性[propName: string]",
          "slug": "_4、任意属性-propname-string"
        },
        {
          "level": 3,
          "title": "5、只读属性 readonly",
          "slug": "_5、只读属性-readonly"
        },
        {
          "level": 3,
          "title": "6、添加函数",
          "slug": "_6、添加函数"
        }
      ]
    },
    {
      "title": "主题",
      "frontmatter": {},
      "regularPath": "/zh/guide/theme.html",
      "relativePath": "zh/guide/theme.md",
      "key": "v-9192ae08",
      "path": "/zh/guide/theme.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "主题列表",
          "slug": "主题列表"
        }
      ]
    },
    {
      "title": "插件",
      "frontmatter": {},
      "regularPath": "/zh/guide/plugin.html",
      "relativePath": "zh/guide/plugin.md",
      "key": "v-483a389a",
      "path": "/zh/guide/plugin.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "插件列表",
          "slug": "插件列表"
        },
        {
          "level": 3,
          "title": "小众插件",
          "slug": "小众插件"
        },
        {
          "level": 3,
          "title": "官方插件",
          "slug": "官方插件"
        }
      ]
    },
    {
      "title": "基础类型",
      "frontmatter": {},
      "regularPath": "/zh/guide/baseDataType.html",
      "relativePath": "zh/guide/baseDataType.md",
      "key": "v-13775f1a",
      "path": "/zh/guide/baseDataType.html",
      "headers": [
        {
          "level": 2,
          "title": "配置环境",
          "slug": "配置环境"
        },
        {
          "level": 2,
          "title": "字符串类型",
          "slug": "字符串类型"
        },
        {
          "level": 2,
          "title": "数字类型",
          "slug": "数字类型"
        },
        {
          "level": 2,
          "title": "布尔类型",
          "slug": "布尔类型"
        },
        {
          "level": 2,
          "title": "空值类型",
          "slug": "空值类型"
        },
        {
          "level": 2,
          "title": "Null和undefined类型",
          "slug": "null和undefined类型"
        }
      ]
    },
    {
      "title": "资源列表",
      "frontmatter": {},
      "regularPath": "/zh/resource.html",
      "relativePath": "zh/resource.md",
      "key": "v-72d17cad",
      "path": "/zh/resource.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/guide/function.html",
      "relativePath": "zh/guide/function.md",
      "key": "v-5c8be7ba",
      "path": "/zh/guide/function.html",
      "headers": [
        {
          "level": 3,
          "title": "1、函数的可选参数",
          "slug": "_1、函数的可选参数"
        },
        {
          "level": 3,
          "title": "2、函数参数的默认值",
          "slug": "_2、函数参数的默认值"
        },
        {
          "level": 3,
          "title": "3、接口的方式定义函数",
          "slug": "_3、接口的方式定义函数"
        }
      ]
    }
  ],
  "themeConfig": {
    "locales": {
      "/": {
        "selectText": "Languages",
        "label": "English",
        "ariaLabel": "Languages",
        "editLinkText": "Edit this page on GitHub",
        "serviceWorker": {
          "updatePopup": {
            "message": "New content is available.",
            "buttonText": "Refresh"
          }
        },
        "algolia": {},
        "nav": [
          {
            "text": "Guide",
            "link": "/guide/",
            "ariaLabel": "Guide"
          },
          {
            "text": "Study",
            "link": "https://lwebapp.com",
            "ariaLabel": "Study"
          },
          {
            "text": "Github",
            "link": "https://github.com/openHacking/vuepress-template"
          }
        ],
        "sidebar": {
          "/guide/": [
            "",
            "theme",
            "plugin"
          ],
          "/resource/": []
        }
      },
      "/zh/": {
        "selectText": "选择语言",
        "label": "简体中文",
        "editLinkText": "在 GitHub 上编辑此页",
        "serviceWorker": {
          "updatePopup": {
            "message": "发现新内容可用.",
            "buttonText": "刷新"
          }
        },
        "algolia": {},
        "nav": [
          {
            "text": "指南",
            "link": "/zh/guide/",
            "ariaLabel": "指南"
          },
          {
            "text": "学习",
            "link": "https://lwebapp.com",
            "ariaLabel": "学习"
          },
          {
            "text": "Github",
            "link": "https://github.com/openHacking/vuepress-template"
          }
        ],
        "sidebar": {
          "/zh/guide/": [
            "",
            "theme",
            "plugin",
            "baseDataType"
          ],
          "/zh/resource/": []
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "Ts_notes",
      "description": "VuePress template, theme, and plugin Demo. The purpose is that users can directly clone this repository as a startup project for initializing a VuePress website, and then add custom configurations and functions based on this project.",
      "path": "/"
    },
    "/zh/": {
      "lang": "zh-CN",
      "title": "Ts_notes",
      "description": "VuePress模板，主题，插件演示。展示了一个简单的VuePress案例模板，用户可以直接clone这个仓库，作为初始化一个VuePress网站启动项目，在这个项目的基础上新增自定义配置和功能。",
      "path": "/zh/"
    }
  }
}